// Generated by gencpp from file pick_and_place/DetectedObjectsStamped.msg
// DO NOT EDIT!


#ifndef PICK_AND_PLACE_MESSAGE_DETECTEDOBJECTSSTAMPED_H
#define PICK_AND_PLACE_MESSAGE_DETECTEDOBJECTSSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <pick_and_place/DetectedObject.h>

namespace pick_and_place
{
template <class ContainerAllocator>
struct DetectedObjectsStamped_
{
  typedef DetectedObjectsStamped_<ContainerAllocator> Type;

  DetectedObjectsStamped_()
    : header()
    , detected_objects()  {
    }
  DetectedObjectsStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detected_objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::pick_and_place::DetectedObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::pick_and_place::DetectedObject_<ContainerAllocator> >> _detected_objects_type;
  _detected_objects_type detected_objects;





  typedef boost::shared_ptr< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedObjectsStamped_

typedef ::pick_and_place::DetectedObjectsStamped_<std::allocator<void> > DetectedObjectsStamped;

typedef boost::shared_ptr< ::pick_and_place::DetectedObjectsStamped > DetectedObjectsStampedPtr;
typedef boost::shared_ptr< ::pick_and_place::DetectedObjectsStamped const> DetectedObjectsStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator1> & lhs, const ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detected_objects == rhs.detected_objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator1> & lhs, const ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_and_place

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94f8531a21eceed11f32889486790c82";
  }

  static const char* value(const ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94f8531a21eceed1ULL;
  static const uint64_t static_value2 = 0x1f32889486790c82ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_and_place/DetectedObjectsStamped";
  }

  static const char* value(const ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"pick_and_place/DetectedObject[] detected_objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: pick_and_place/DetectedObject\n"
"float64 x_world\n"
"float64 y_world\n"
"float64 z_world\n"
"float64 width\n"
"float64 length\n"
"float64 height\n"
"string color\n"
;
  }

  static const char* value(const ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detected_objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedObjectsStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_and_place::DetectedObjectsStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detected_objects[]" << std::endl;
    for (size_t i = 0; i < v.detected_objects.size(); ++i)
    {
      s << indent << "  detected_objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pick_and_place::DetectedObject_<ContainerAllocator> >::stream(s, indent + "    ", v.detected_objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_AND_PLACE_MESSAGE_DETECTEDOBJECTSSTAMPED_H
